name: Update External PRs

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write  # needed to push changes

jobs:
  update-prs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Fetch recent merged PRs using GitHub Script
      - name: Fetch recent merged PRs
        id: fetch_prs
        uses: actions/github-script@v6
        with:
          script: |
            // Fetch the last 5 merged PRs authored by you
            const { data } = await github.rest.search.issuesAndPullRequests({
              q: "author:hamzakhan977 type:pr is:merged",
              sort: "updated",
              order: "desc",
              per_page: 5
            });

            if (!data.items || data.items.length === 0) {
              core.setOutput("content", "No recent contributions found.");
              return;
            }

            // Map to markdown list
            const list = data.items.map(pr => {
              const repo = pr.repository_url.replace("https://api.github.com/repos/", "");
              return `- [${pr.title}](${pr.html_url}) in **${repo}**`;
            });

            const content = list.join("\n");
            console.log("=== Generated PR Content ===\n" + content);
            core.setOutput("content", content);

      # 3. Insert PRs into README.md
      - name: Insert PRs into README
        run: |
          CONTENT="${{ steps.fetch_prs.outputs.content }}"
          START="<!-- external-prs:start -->"
          END="<!-- external-prs:end -->"

          TMP=$(mktemp)
          inside=0
          while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ "$line" == "$START" ]]; then
              echo "$line" >> "$TMP"
              echo "$CONTENT" >> "$TMP"
              inside=1
              continue
            fi
            if [[ "$line" == "$END" ]]; then
              inside=0
            fi
            if [[ $inside -eq 0 ]]; then
              echo "$line" >> "$TMP"
            fi
          done < README.md

          mv "$TMP" README.md

      # 4. Debug: print the README snippet
      - name: Show updated snippet
        run: |
          awk '/<!-- external-prs:start -->/{f=1;next}/<!-- external-prs:end -->/{f=0}f' README.md

      # 5. Commit and push changes
      - name: Commit & push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "docs: update recent merged PRs" --allow-empty
          git push
