name: Update Contributors List

on:
  schedule:
    - cron: '0 6 * * *'     # every day at 06:00 UTC
  workflow_dispatch:        # manual trigger

permissions:
  contents: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Contributors list
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        with:
          image_size: 100
          readme_path: README.md
          columns_per_row: 6
          commit_message: "docs: update contributors list"

      - name: Commit & push changes (if any)
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && echo "No changes in README.md" || git commit -m "chore: update contributors" && git push
