name: Update External PRs

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch recent merged PRs
        id: fetch_prs
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.request("GET /search/issues", {
              q: "is:pr is:merged author:hamzakhan977",
              sort: "updated",
              order: "desc",
              per_page: 5
            });

            if (!data.items || data.items.length === 0) {
              core.setOutput("content", "No recent contributions found.");
              return;
            }

            const list = data.items.map(pr => {
              const repo = pr.repository_url.split("/").slice(-2).join("/");
              return `- [${pr.title}](${pr.html_url}) in **${repo}**`;
            });

            core.setOutput("content", list.join("\n"));

      - name: Update README
        run: |
          CONTENT="${{ steps.fetch_prs.outputs.content }}"
          awk -v content="$CONTENT" '
            /<!-- external-prs:start -->/ {print; print content; found=1; next}
            /<!-- external-prs:end -->/ {found=0}
            !found
          ' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit & push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "docs: update recent PRs" && git push
