name: Update External PRs

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v3

      - name: Fetch recent merged PRs
        id: fetch_prs
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.request("GET /search/pulls", {
              q: "author:hamzakhan977 is:merged",
              sort: "updated",
              order: "desc",
              per_page: 5
            });

            if (!data.items || data.items.length === 0) {
              core.setOutput("content", "No recent contributions found.");
              return;
            }

            const list = data.items.map(pr => {
              const repo = pr.base.repo.full_name;
              return `- [${pr.title}](${pr.html_url}) in **${repo}**`;
            });

            core.setOutput("content", list.join("\n"));

      - name: Fetch recent merged PRs
        id: fetch_prs
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.search.issuesAndPullRequests({
              q: "author:hamzakhan977 type:pr is:merged",
              sort: "updated",
              order: "desc",
              per_page: 5
            });
      
            if (!data.items || data.items.length === 0) {
              core.setOutput("content", "No recent contributions found.");
              return;
            }
      
            const list = data.items.map(pr => {
              const repo = pr.repository_url.replace("https://api.github.com/repos/", "");
              return `- [${pr.title}](${pr.html_url}) in **${repo}**`;
            });
      
            core.setOutput("content", list.join("\n"));

          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "docs: update recent PRs" && git push
