name: Update Open Source PRs

on:
  schedule:
    - cron: '0 6 * * *'   # every day at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update merged PRs
        uses: satyawikananda/github-contributions-readme-action@v2.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          readme-path: ./README.md
          number: 5
          include-merges: true
          filter: PR
          section-name: contribs
